### ISSUE TITLE
昨天的新版和其他MOD合装的崩溃报告

### ISSUE THREAD

**Issue by canglllll** [IdeallandEarthDept/ReleasingMods#1]
大佬，你的空岛和别的生态群系有冲突，关了交错次元和匠魂还有别的冲突

[crash-2021-12-25_16.39.21-client.txt](https://github.com/IdeallandEarthDept/ReleasingMods/files/7775658/crash-2021-12-25_16.39.21-client.txt)
[crash-2021-12-25_04.29.55-client.txt](https://github.com/IdeallandEarthDept/ReleasingMods/files/7775659/crash-2021-12-25_04.29.55-client.txt)

**Comment by TaoismDeepLake** [comment]
两封日志都不是我的锅。
第一封日志怎么看都是shincolle舰娘mod出了问题；
第二封日志单纯是因为群系过多，超过256个了，并不是我做的东西有问题。第二个日志你可以尝试[安装JEID](https://www.mcmod.cn/class/1389.html)，如果还解决不了只好删几个mod了。

**Comment by TaoismDeepLake** [comment]
(嗯不过我注册的群系确实不少，空岛的16个变种就是16个了，以后我会尽量悠着点
